### ISSUE TITLE
How to hide a widget?

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#54] opened 2023-03-06 10:25 UTC
I tried searching for `Visible` or `Hidden` properties but found none.
Is there a way to hide a widget?

I see a way to disable a widget, but sometimes you want a different state: disabled+invisible (or we can imply that invisible elements are disabled automatically).

**Comment by mcarpenter622** [comment] 2023-03-08 02:36
This is a duplicate of https://github.com/ebitenui/ebitenui/issues/37

**Closed as not planned by mcarpenter622** 2023-03-08 02:36 UTC
